### ISSUE TITLE
How does the stance check verified?

### ISSUE THREAD

**Issue by debpalash** [WeAreMahsaAmini/CelebrityWall#17]
![image](https://user-images.githubusercontent.com/4178343/193400341-4cdeceba-475a-41ca-a509-059cd837701c.png)

Is this a random function that is saying which celeb is against or with?

**Comment by farnoodma** [comment]
Right now data is fake, we are still waiting for our content team to provide us with real data. The current content is just for test purposes.

**Comment by debpalash** [comment]
> Right now data is fake, we are still waiting for our content team to provide us with real data. The current content is just for test purposes.

Then you should mention it's fake data.
