### ISSUE TITLE
Different statuses on refreshing page | runtime bug

### ISSUE THREAD

**Issue by mehdi-ra** [WeAreMahsaAmini/CelebrityWall#19]
Hey, I was exploring the [Wall](https://wall.wearemahsaamini.com) page for problems, then I noticed that there is something weird going on with the wall
I tried to create a Gif image to describe the problem better from 3 times refreshed screenshots:
![diff-status on refers](https://i.postimg.cc/LXTtrSbD/6vdjrf.gif)

It needs to be debugged.

**Comment by farnoodma** [comment]
Hey, our current data is fake and is only for test purposes, that's why the status of each celebrity changes each time. This will be solved as soon as we replace the data with an actual one.
