### ISSUE TITLE
Link the tweet that shows the celebrity's support

### ISSUE THREAD

**Issue by zhinamaya** [WeAreMahsaAmini/CelebrityWall#20]
Now, when the user clicks on the celebrity's thumbnail, they will be transferred to the celebrity's profile which shows the profile picture and latest tweet which is a somehow irrelevant. I think instead it should display that particular tweet which shows their support.

**Comment by farnoodma** [comment]
Hey, it will show the Tweet that is related. However, since the current data is fake and for test purposes only, it is not correct. It will be solved as soon as we replace it with actual real data.
