### ISSUE TITLE
Add their message! 

### ISSUE THREAD

**Issue by amirnazari96** [WeAreMahsaAmini/CelebrityWall#3]
We should put their tweet, story, post, or anything that they did!

**Comment by nazunderground** [comment]
Totally agree, this makes it so much more powerful! What if, when you click the image their response opens like a lite box.

**Comment by firiz** [comment]
@anazari96 @nazunderground This has been implemented. If you click on each celebrity, you can see the tweet they made. Just waiting for the data to be compiled so we can replace it with the mock data.
